### ISSUE TITLE
Documentation around literals misleading

### ISSUE THREAD

**Issue by SamRaymer** [mreinstein/alexa-utterances#15]
Amazon is deprecating the use of Literals in Alexa by Nov 30 2016. It was a little hard to read the README.md in the context of this, although I assume we can count on using the custom slot syntax in the future. 

Great stuff! 
Cheers

**Comment by SamRaymer** [comment]
I forgot to check my calendar when I wrote this -- literals are deprecated already!

Thanks again

**Comment by mreinstein** [comment]
@SamRaymer what's the actionable thing in this case?

**Comment by mreinstein** [comment]
closing this due to no actionable details.
