### ISSUE TITLE
Would you like to move this repo into the alexa-js organization?

### ISSUE THREAD

**Issue by dblock** [mreinstein/alexa-utterances#18]
Would you like to move this repo into the newly created alexa-js organization, https://github.com/alexa-js?

This would reduce bus factor as currently only @mreinstein can add contributors to this project. By moving org admins can at least add new people, currently that's @matt-kruse and myself.

If you do want to do this, because Github requires one be admin of both source and destination, transfer the repo to me (@dblock) and I'll immediately move it to the org.

**Comment by dblock** [comment]
https://github.com/alexa-js

**Comment by mreinstein** [comment]
It depends on the intentions of the org. I'm all for the enabling contributors, but what I don't want to see happen is a move towards some monolithic or framework based system.

node and npm are a joy to work with because these modules follow the unix philosophy of each doing one small thing, and doing it very well (at least, the good modules follow this approach.)

I cringe at the thought of this becoming some big platform where the modules become less useful as individual units.

What does the org intend to do with this code? Is there going to be some push to move things torwards a shiny "alexajs" platform, or will the code be maintained in it's current state?

**Comment by dblock** [comment]
Thanks @mreinstein for replying! 

There're no goals or plans for the organization at all, except reducing bus factor and creating a place for similar or related projects to make them more discoverable. There're no plans to try to make things into a bigger framework or to take over your project by any means. You still very much own your modules and manage them and do whatever you want in them, but now if a piano falls on your head (hopefully not) there're some org maintainers that can cover for you. At the most I'd encourage you to grow the list of maintainers within these projects.

So to be clear: 

1) the org is going to do nothing with your code
2) there will be no "push"

Hope this helps.

**Comment by dblock** [comment]
Btw, I maintain two similar orgs: https://github.com/ruby-grape/ and https://github.com/slack-ruby

**Comment by mreinstein** [comment]
@dblock sounds reasonable. How do I go about assimilation into this alexa borg collective? : )

**Comment by dblock** [comment]
Haha.

Transfer the repos to me and I'll immediately move them into alexa-js.

**Comment by mreinstein** [comment]
should I just transfer them to `alexa-js` org?

**Comment by mreinstein** [comment]
i.e., this? 
<img width="562" alt="screen shot 2017-01-12 at 12 25 31 pm" src="https://cloud.githubusercontent.com/assets/718067/21906948/418e3928-d8c2-11e6-8cb7-329484d6a9ed.png">

**Comment by dblock** [comment]
Except you aren't admin of the org and it won't let you. But I am happy to give you org admin access too, should I?

**Comment by dblock** [comment]
Welcome to the borg :)

I think you'd be a great third admin for the alexa-js org too @mreinstein as you've written two of the essential packages for alexa-app, so I made you org admin as well. LMK if you _don't_ want the responsibility.

Consider adding me and/or @matt-kruse to npm as well, that will permanently solve the bus factor problem ;)

**Comment by mreinstein** [comment]
I've added you and Matt to both packages on npm
