### ISSUE TITLE
Tabs after intent name causing issues pasting to Amazon

### ISSUE THREAD

**Issue by scullum** [mreinstein/alexa-utterances#28]
I have been writing out the output of the utterances to a file. From there I need to paste it into the developer console. The issue arose last night as my interaction model was not saved. I did a bit of research and it came down to a tab character between the intent and the utterance. Sure enough if I replace the tab with a space Amazon does not balk. I realize this is on Amazon a bit but ATM its a bit fragile. Any chance of changing the delimiter to a space vs. a tab?

**Comment by dblock** [comment]
This is a recent change from Amazon. In alexa-app this was fixed in https://github.com/alexa-js/alexa-app/pull/204, possibly this project also needs a PR, please.
