### ISSUE TITLE
Custom Slot support

### ISSUE THREAD

**Issue by arch1v1st** [mreinstein/alexa-utterances#8]
This patch is currently needed to support custom slot types:

https://github.com/MaxwellPayne/alexa-utterances/commit/8599208037ada7020a3ab8c6fc979e31a2ff934c

Would you be willing to apply this change to master/npm?

Thanks a lot!

**Comment by arch1v1st** [comment]
...BUMP...

Please consider applying this to master/npm - will make installing ASK's which depend on custom slots considerably easier (i.e. with no patching involved).

Thanks either way!  :)

**Comment by arch1v1st** [comment]
FYI - Purely coincidental, I came across this [post](https://www.bignerdranch.com/blog/developing-alexa-skills-locally-with-nodejs-deploying-your-skill-to-staging/) on LinkedIn just now; noticed a comment where a user was facing the same custom slot issue.  The author added a [hack](https://github.com/bignerdranch/alexa-airportinfo/blob/master/index.js#L43)  which is a one line regex to address the problem.

**Comment by doapp-ryanp** [comment]
@mreinstein are you able to add this? Great module you have here but this is a pretty big gap at the moment.

**Comment by mreinstein** [comment]
we've pushed alexa-utterances@0.2.0 which provides custom slot support.
